### DISCUSSION TITLE
Can I have a guest login?

### DISCUSSION THREAD

**Discussion by chattytak** [kubernetes-csi/csi-driver-smb#455] [Q&A]
I tried to login as a guest, but it didn't work because of a parameter error.
Is guest login supported?

**Comment by andyzhangx** [comment]
what does `guest login` mean? do you have more details? @chattytak

**Reply by chattytak** [reply]
I mean the standard option for cifs, which eliminates the need for username and password.`-o guest`

**Reply by andyzhangx** [reply]
if you run `mount -t cifs -o guest ...`, and works on that agent node, I think that should also work with this CSI driver.

**Reply by chattytak** [reply]
I added the guest option as in this config. In addition, I removed the credential specification. However, the `-o username=` specification seems to be hard coded and causes an option error.

```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb
provisioner: smb.csi.k8s.io
parameters:
  # On Windows, "*.default.svc.cluster.local" could not be recognized by csi-proxy
  source: "//smb-server.default.svc.cluster.local/share"
  # if csi.storage.k8s.io/provisioner-secret is provided, will create a sub directory
  # with PV name under source
  #csi.storage.k8s.io/provisioner-secret-name: "smbcreds"
  #csi.storage.k8s.io/provisioner-secret-namespace: "default"
  #csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  #csi.storage.k8s.io/node-stage-secret-namespace: "default"
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverino  # required to prevent data corruption
  - guest
```

**Comment by andyzhangx** [comment]
`username` and `password` is hardcoded now, could you make sure `mount -t cifs -o guest ...` on your agent node? I could make a code change to support `guest` mount option later.

**Reply by andyzhangx** [reply]
so when `guest` option is provided, `password` option is not needed, and `username` is still required, right?

**Reply by chattytak** [reply]
If `map to guest = Bad User` is present in smb.conf, it is not necessary to specify the user by username=, since it will fall back to the Guest login if the user name is mistaken.
At least I can mount it successfully with the following command on the normal command line.
`mount.cifs -o guest //${FQDN}/smb/ /mnt/smb/`

**Reply by andyzhangx** [reply]
this PR(https://github.com/kubernetes-csi/csi-driver-smb/pull/457) should fix the issue.
are you able to try `mcr.microsoft.com/k8s/csi/smb-csi:latest` on daemonset on agent node? run `kubectl edit ds csi-smb-node -n kube-system`, and replace with `mcr.microsoft.com/k8s/csi/smb-csi:latest`

**Reply by chattytak** [reply]
I am able to log in as guest without specifying credentials.
However, I am experiencing an event where a subdirectory starting with "pvc-" is not created in the shared folder, and the root directory of the shared folder is mounted directly.
I have searched past issues and it seems similar to this event. #307
Is it possible that the credential specification is no longer required, resulting in unintended behavior?

**Reply by andyzhangx** [reply]
for this case, looks like we still need `createSubDir: "true"` in parameters, I have removed that parameter because the createSubDir could be controlled by `provisioner-secret-name`: 
https://github.com/kubernetes-csi/csi-driver-smb/blob/b55cdbd0f38bcd30bab9b1030cb50fa880bb075a/deploy/example/storageclass-smb.yaml#L10-L15

**Reply by andyzhangx** [reply]
I think you could try a simple workaround, just define a dummy secret, and then it would create subDir:
```yaml
parameters:
   csi.storage.k8s.io/provisioner-secret-name: "smbcreds" 
   csi.storage.k8s.io/provisioner-secret-namespace: "default" 
```
