### DISCUSSION TITLE
Unable to mount when authenticating with Kerberos

### DISCUSSION THREAD

**Discussion by davidnraines** [kubernetes-csi/csi-driver-smb#545] [Q&A]
We are attempting to use csi-driver-smb v1.9.0.  We are running k3s on RHEL 8.6, with FIPS mode enabled.  We are connecting to an SMB share, and attempting to use Kerberos to authenticate.

Our Kerberos keytab is here:  [krb5.conf](https://github.com/kubernetes-csi/csi-driver-smb/files/9686463/krb5.txt)

When we run the mount command manually, we would use this:
`> mount -t cifs -o sec=krb5,vers=2.0 //SMBHOST/path /mnt/testmount`
And this works.

When we attempted to use the PV / PVC implementation, this was our PersistentVolume:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb
  namespace: myapp
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - sec=krb5
    - vers=2.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: unique-volumeid 
    volumeAttributes:
      source: "//SMBHOST/path/"
```

This is the error message we see:
```
Mounting command: mount
Mounting arguments: -t cifs -o sec=krb5,vers=2.0,username=<masked> //SMBHOST/path /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb/globalmount
Output: username specified with no parameter
```

Our suspicion is that the option _username=""_ is being added to the options, but its hard to verify.

Are we doing anything obviously wrong?  Is this sort of Kerberos authentication supported by this tool?  

Thank you for your time, and we'd appreciate any help.
