### DISCUSSION TITLE
Mount options not being used?

### DISCUSSION THREAD

**Discussion by luke-barnett** [kubernetes-csi/csi-driver-smb#939] [Q&A] [answered]
I need to set uid and gid for proper permissions within a container and I can't seem to get the it working as expected.

Here is my pv

```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: pv-storage-smb
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0755
    - file_mode=0644
    - uid=1000
    - gid=1000
    - forceuid
    - forcegid
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: data.host/storage##pv
    volumeAttributes:
      source: "//data.host/storage"
    nodeStageSecretRef:
      name: smb-creds
      namespace: csi-driver-smb
```

When checking the mounts on the node and from the container it's all still set as uid=0?

Checking the mount definitions on the host I have by running `mount | grep cifs` I get the following:

> //data.host/storage on /var/lib/kubelet/pods/37205acf-fb2b-4a0c-8a5b-f0857e8407da/volumes/kubernetes.io~csi/pv-storage-smb/mount type cifs (rw,relatime,vers=3.1.1,cache=strict,username=srv-k3s,uid=0,noforceuid,gid=0,noforcegid,addr=<ip>,file_mode=0777,dir_mode=0777,soft,nounix,serverino,mapposix,rsize=4194304,wsize=4194304,bsize=1048576,retrans=1,echo_interval=60,actimeo=1,closetimeo=1)

which to me suggests that it's completely ignoring the mount options? I manually mounted the same share with uid/gid settings to confirm that the host/server supports those mount options and that worked fine. Not sure what I'm missing?
