### ISSUE TITLE
Attach pvc name to pv

### ISSUE THREAD

**Issue by varac** [kubernetes-csi/csi-driver-smb#108]
**Is your feature request related to a problem?/Why is this needed**

When you have muliple PVs, it becomes hard to find your data since the PV names are just random UIDs.

```
root@oas2:~# kubectl -n default get pvc                                                                                                                                                  
NAME                                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE                                                  
persistent-storage-statefulset-smb-0   Bound    pvc-9e4a8166-47c6-4996-ba0b-b16508e381dd   10Gi       RWO            smb            26s                                                  
```

**Describe the solution you'd like in detail**

I'd like to have the PVC name (and namespace) attached in the PV name, similar to how [ranchers local-path-provisioner](https://github.com/rancher/local-path-provisioner/pull/78/files) does it.

**Describe alternatives you've considered**

None

**Additional context**

Example of expected outcome:

```
root@oas2:~# kubectl -n default get pvc                                                                                                                                                  
NAME                                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE                                                  
persistent-storage-statefulset-smb-0   Bound    pvc-9e4a8166-47c6-4996-ba0b-b16508e381dd-default-persistent-storage-statefulset-smb-0  10Gi       RWO            smb            26s                                                  
```

**Comment by varac** [comment]
I just realized that [ranchers local-path-provisioner](https://github.com/rancher/local-path-provisioner/) doesn't add the PVC name and namespace to the PV name, but instead to the directory name it creates:

```
root@oas:~# ls /var/lib/OpenAppStack/local-storage/
pvc-1f16e7ce-26dd-4da9-b0d0-e9b0cff3656c_oas_single-sign-on-userbackend  pvc-8a506b74-000f-4160-9120-7736dd819f34_oas_prometheus-server
pvc-7b4f8df8-72f5-4112-a05f-c5565488f21f_oas_alertmanager		pvc-defdf73a-bccf-4f19-b147-e32088ea5f3b_oas_grafana
```

Which already helps a lot when you are investigating your PVs

**Comment by andyzhangx** [comment]
I think that's by design, we don't control PV/PVC name in csi driver

**Comment by varac** [comment]
I don't understand, isn't the PV name/directory created by the csi-driver-smb ?

**Comment by andyzhangx** [comment]
there is `createSubDir: "true"` in storage class, that would create a new directory, I think that would help:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb
provisioner: smb.csi.k8s.io
parameters:
  source: "//smb-server.default.svc.cluster.local/share"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "default"
  createSubDir: "true"  # optional: create a sub dir for new volume
```
