### ISSUE TITLE
Cannot access to mounted volume from container (permssion denied) (selinux enabled)

### ISSUE THREAD

**Issue by flaviopicci** [kubernetes-csi/csi-driver-smb#132]
Hi everyone,
I'm trying to consume CIFS shares from an OpenShift (OKD) 4 cluster using this CSI driver.

**What happened**:
When I try to access a mounted CIFS folder from a container I get a permission denied error. Here is the ls output from a centos:8 container with the CIFS folder mounted under /mnt/smb:
```
sh-4.4$ ls -l /mnt/
ls: cannot access '/mnt/smb': Permission denied
total 0
d????????? ? ? ? ?            ? smb
```
However if I log into the physical machine, I can see the shared folder correctly mounted under `/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-cifs/globalmount` and I can access it as I would expect.

I suspect that the error might be due to the SELinux label applied to the globalmount folder (cifs_t instead of container_file_t):
```
[root@master1 pvc-cifs]# ls -alZ
total 16
drwxr-x---. 3 root root system_u:object_r:container_file_t:s0    46 Oct  5 15:32 .
drwxr-x---. 4 root root system_u:object_r:container_file_t:s0    80 Oct  5 15:32 ..
drwxrwxrwx. 2 root root system_u:object_r:cifs_t:s0           12288 Sep 18 20:54 globalmount
-rw-r--r--. 1 root root system_u:object_r:container_file_t:s0    68 Oct  5 15:32 vol_data.json
```
Here is the (correct?) SELinux labels of a mounted Ceph RBD volume with the ROOK CSI driver:
```
[root@master1 pvc-14f0f04d-85fd-452b-aac4-848d3c2bd3c3]# ls -alZ
total 4
drwxr-x---. 3 root root system_u:object_r:container_file_t:s0    46 Oct  5 15:32 .
drwxr-x---. 4 root root system_u:object_r:container_file_t:s0    80 Oct  5 15:32 ..
drwxr-x---. 3 root root system_u:object_r:container_file_t:s0 110 Oct  2 13:03 globalmount
-rw-r--r--. 1 root root system_u:object_r:container_file_t:s0 135 Oct  2 13:03 vol_data.json
```

As I used to do when manually mounting CIFS shares in containers, I also tried to add `context="system_u:object_r:container_file_t:s0"` as a mountOption of the PV, but the result is the same.

Here is the mount from `/proc/mounts` (it is the same with or without "context="):
```
[root@master1 ~]# cat /proc/mounts
...
//myhost.local/someshared /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-cifs/globalmount cifs rw,relatime,vers=3.0,cache=strict,username=xxxxxx,domain=xxxx.local,uid=0,noforceuid,gid=0,noforcegid,addr=10.150.120.104,file_mode=0666,dir_mode=0777,soft,nounix,serverino,mapposix,rsize=4194304,wsize=4194304,bsize=1048576,echo_interval=60,actimeo=1 0 0
//myhost.local/someshared /var/lib/kubelet/pods/4a688e32-70ff-4f48-8318-4b9655594163/volumes/kubernetes.io~csi/pvc-cifs/mount cifs rw,relatime,vers=3.0,cache=strict,username=xxxxxx,domain=xxxx.local,uid=0,noforceuid,gid=0,noforcegid,addr=10.150.120.104,file_mode=0666,dir_mode=0777,soft,nounix,serverino,mapposix,rsize=4194304,wsize=4194304,bsize=1048576,echo_interval=60,actimeo=1 0 0
...
```

Am I missing something? Any help is appreciated.

Thanks,
Flavio

**What you expected to happen**:
Correctly access the shared folder.

**How to reproduce it**:
Using my configuration it always happen:
```yaml
# cifs-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cifs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: smb.csi.k8s.io
    volumeAttributes:
      source: //myhost.local/someshared
    volumeHandle: pv-cifs-someshared
    nodeStageSecretRef:
      name: sec-cifs
      namespace: kube-system
  mountOptions:
  - dir_mode=0777
  - file_mode=0666
  - vers=3.0
# - context="system_u:object_r:container_file_t:s0"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
```
```yaml
# cifs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cifs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-cifs
```

**Anything else we need to know?**:
I installed the CSI driver with the following commands
`oc create -f https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/deploy/csi-smb-driver.yaml`
`oc create -f https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/deploy/csi-smb-node.yaml`

**Environment**:
- CSI Driver version: **latest**
- Kubernetes version (use `kubectl version`): **v1.18.2-0-g52c56ce**
- OpenShift version (use `oc version`): **4.5.0-0.okd-2020-09-18-202631**
- OS (e.g. from /etc/os-release): **Fedora CoreOS 32.20200629.3.0**
- Kernel (e.g. `uname -a`): **5.6.19-300.fc32.x86_64**
- SELinux status (/etc/selinux/config): **SELINUX=enforcing SELINUXTYPE=targeted**

**Comment by andyzhangx** [comment]
could you try run that container as root user:
```
spec:
  securityContext:
    runAsUser: 0
    fsGroup: 0
```

**Comment by flaviopicci** [comment]
Thanks for the reply. What you suggested did not work, but I tried something similar that worked.
I had to run the container as privileged with a particular SCC, this way the read/write permission is granted. I think this is specific to OpenShift:
```yaml
spec:
  securityContext:
    privileged: true
# any user is ok
```
Anyway, even if this is accettable, it's not desired in production. Is there any way to set the "correct" SELinux label or something to avoid the privileged container?

Thanks,
Flavio
