### ISSUE TITLE
Update Usage of CSI Provisioner in csi-smb-controller

### ISSUE THREAD

**Issue by kferrone** [kubernetes-csi/csi-driver-smb#145]
**What happened**:
I tried to run the chart on nodes with `arm64` and the CSI Provisioner image must be `v2.0.4` to support multiarch. The current version in the chart is defaulted to `v1.4.0` which does not have a multiarch build and therefore will not run on `arm64`. 

If I use the default repository of: `mcr.microsoft.com/oss/kubernetes-csi/csi-provisioner:v2.0.4`; then I can't even pull the image. 

If I use `k8s.gcr.io/sig-storage/csi-provisioner:v2.0.4`; then the image pulls and actually runs on `arm64`. 
However I do get this error:
```
unknown flag: --enable-leader-election
Usage of /csi-provisioner:
unknown flag: --enable-leader-election
```
Basically it shows a big list of flags that can be used and `--enable-leader-election` is actually not an option, nor is it here: https://github.com/kubernetes-csi/external-provisioner

I tracked down the [csi-smb-controller file](https://github.com/kubernetes-csi/csi-driver-smb/blob/master/charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml), it seems it needs an update to the args.

**What you expected to happen**:
Correctly run the latest and greatest `csiProvisioner` with up to date flags. This way Arm64 is one step closer to using smb-csi. 

**How to reproduce it**:
Here is my values.yaml to run on some arm nodes:
```yaml
image:
  smb:
    tag: latest
  csiProvisioner:
    repository: k8s.gcr.io/sig-storage/csi-provisioner
    # tag: v1.6.1
    tag: v2.0.4
  livenessProbe:
    repository: k8s.gcr.io/sig-storage/livenessprobe
    tag: v2.1.0
  nodeDriverRegistrar:
    repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    tag: v2.0.1
```
