### ISSUE TITLE
Suggest on shipping a custom PodSecurityPolicy for csi-smb-node

### ISSUE THREAD

**Issue by joschi36** [kubernetes-csi/csi-driver-smb#155]
**Is your feature request related to a problem?/Why is this needed**
When using a default restrictive PodSecurityPolicy in the cluster you need to have a custom PodSecurityPolicy in order to run the csi-smb-node DaemonSet.

**Describe the solution you'd like in detail**
An additional manifest containing a PodSecurityPolicy for csi-smb-node.

**Describe alternatives you've considered**
Creating an own PSP.

**Additional context**
Here I have an example of the PSP I created for my case, I think this could be used as a default.
Even If you opt to not integrate in the repo other people can find this PSP in the GitHub issues ;)

```yaml
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: csi-smb-node
spec:
  allowedHostPaths:
  - pathPrefix: /var/lib/kubelet/plugins/smb.csi.k8s.io
  - pathPrefix: /var/lib/kubelet/
  - pathPrefix: /var/lib/kubelet/plugins_registry/
  fsGroup:
    rule: RunAsAny
  hostNetwork: true
  hostPorts:
  - max: 29643
    min: 29643
  - max: 29645
    min: 29645
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - hostPath
  - secret
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-smb-node
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - csi-smb-node
  verbs:
  - use
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-smb-node
subjects:
- kind: ServiceAccount
  name: csi-smb-node-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-smb-node
  apiGroup: rbac.authorization.k8s.io
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: csi-smb-node-sa
  namespace: kube-system
```

Change your DaemonSet in order to use the created ServiceAccount.
