### ISSUE TITLE
[Windows]A specified logon session does not exist. It may already have been terminated

### ISSUE THREAD

**Issue by junneyang** [kubernetes-csi/csi-driver-smb#161]
mount error: A specified logon session does not exist. It may already have been terminated

windows: 2019
k8s: v1.17.2

yaml config:
```
        volumeMounts:
        - name: smb-volume
          mountPath: /sharestorage
      volumes:
      - name: smb-volume
        flexVolume:
          driver: "microsoft.com/smb.cmd"
          secretRef:
            name: "smb-secret"
          options:
            source: \\xxxxxxx.xxxxxxx.com\share-2d58d4ca
---
apiVersion: v1
kind: Secret
type: microsoft.com/smb.cmd
metadata:
  name: smb-secret
data:
  username: xxxxxxx
  password: xxxxxxx
```
