### ISSUE TITLE
can "priviledged: true" on the smb container of the csi-smb-node ds be replaced with a set of required capabilities?

### ISSUE THREAD

**Issue by ensonic** [kubernetes-csi/csi-driver-smb#172]
**Is your feature request related to a problem?/Why is this needed**
https://github.com/kubernetes-csi/csi-driver-smb/blob/master/deploy/v0.5.0/csi-smb-node.yaml#L99-L100
uses
```yaml
securityContext:
  privileged: true
```
This is very broad and a concern for production use.

**Describe the solution you'd like in detail**
It would be great to change the securityContext to:
```yaml
securityContext:
capabilities:
    drop:
      - all
    add:
      - ...
```
The [docker documentation](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities) lists the capabilities and what they are for.
