### ISSUE TITLE
Unable to mount SMB volume

### ISSUE THREAD

**Issue by venomone** [kubernetes-csi/csi-driver-smb#175]
Hey,

If I try to mount a volume it always fails with the following error:

```
Warning  FailedMount       13s (x7 over 47s)  kubelet            MountVolume.MountDevice failed for volume "pvc-df7c7e39-98cc-4462-8d1c-a901bced7da9" : rpc error: code = Internal desc = volume(pvc-df7c7e39-98cc-4462-8d1c-a901bced7da9) mount "//abc.storagebox.com/Datastore01" on "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-df7c7e39-98cc-4462-8d1c-a901bced7da9/globalmount" failed with mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t cifs -o dir_mode=0777,file_mode=0777,<masked> //abc.storagebox.com/Datastore01 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-df7c7e39-98cc-4462-8d1c-a901bced7da9/globalmount
Output: mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```
This is how my config looks like:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb
provisioner: smb.csi.k8s.io
parameters:
  source: "//smb-server.default.svc.cluster.local/share"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "echo"
  createSubDir: "false"  # optional: create a sub dir for new volume
reclaimPolicy: Retain  # only retain is supported
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datastore01-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: UB6F8GCQJ2
    volumeAttributes:
      source: "//abc.storagebox.com/Datastore01"
    nodeStageSecretRef:
      name: smbcreds
      namespace: echo
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datastore01
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: smb
```

Can somebody give my a hint what Im doing wrong? I simply want to mount a remote CIFS/SMB share into my container
