### ISSUE TITLE
Mount fails with error no such file or directory

### ISSUE THREAD

**Issue by faandg** [kubernetes-csi/csi-driver-smb#234]
**What happened**:
Received following error while mounting with csi driver version 0.6.0 and latest on OpenShift:
`MountVolume.MountDevice failed for volume "pv-new-smb-audit-self-service-uat" : rpc error: code = Internal desc = volume(vh-pv-new-smb-audit-self-service-uat) mount "//DOMAINX/Global/OCP-A" on "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-new-smb-audit-self-service-uat/globalmount" failed with mount failed: exit status 32 Mounting command: mount Mounting arguments: -t cifs -o dir_mode=0770,file_mode=0770,vers=3.0,<masked> //DOMAINX/Global/OCP-A /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-new-smb-audit-self-service-uat/globalmount Output: mount error(2): No such file or directory Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)`

It looks like the directory `/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-new-smb-audit-self-service-uat` is not being created.

We noticed in a similar bug report that you mentioned a permission issue and provided a possible fix:
https://github.com/kubernetes-csi/csi-driver-smb/issues/132#issuecomment-704652486

We tested the following versions:
- 0.6.0 (without this fix)
- latest (without this fix)
- latest (with this fix)
However the same issue keeps occuring.

PV used:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-new-smb-audit-self-service-uat
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0770
    - file_mode=0770
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: vh-pv-new-smb-audit-self-service-uat
    volumeAttributes:
      source: "//DOMAINX/Global/OCP-A"
    nodeStageSecretRef:
      name: cred-smb-audit-self-service-uat
      namespace: self-service-uat
```

PVC used:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-new-smb-audit-self-service-uat
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: pv-new-smb-audit-self-service-uat
  storageClassName: ""
```

The share itself is hosted on an external DFS.
Where DOMAINX is the domain, Global is the namespace and OCP-A is the share name.

**What you expected to happen**:
Successful mount.

**How to reproduce it**:
Install the latest driver on OCP4.5.15, create PV above , create PVC above, create a pod with mount referencing the PVC.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
`0.6.0 and latest`

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2-0-g52c56ce", GitCommit:"3f6a83fb70bfe5c6ef0e0886923c90015a4256bc", GitTreeState:"clean", BuildDate:"2020-10-08T15:54:21Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+2fbd7c7", GitCommit:"2fbd7c7", GitTreeState:"clean", BuildDate:"2020-10-09T11:41:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (e.g. from /etc/os-release):
```
NAME="Red Hat Enterprise Linux CoreOS"
VERSION="45.82.202010091130-0"
VERSION_ID="4.5"
OPENSHIFT_VERSION="4.5"
RHEL_VERSION="8.2"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 45.82.202010091130-0 (Ootpa)"
ID="rhcos"
ID_LIKE="rhel fedora"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::coreos"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.5"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.5"
OSTREE_VERSION='45.82.202010091130-0'
```

- Kernel (e.g. `uname -a`):
`Linux sainfr00071.domainx 4.18.0-193.24.1.el8_2.dt1.x86_64 #1 SMP Thu Sep 24 14:57:05 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux`

- Install tools:
`Install by kubectl`

- Others:
Thanks in advance
