### ISSUE TITLE
smbplugin.exe resulting in Windows nodes and causing blue screens

### ISSUE THREAD

**Issue by WangMosquito** [kubernetes-csi/csi-driver-smb#261]
**What happened**:
Working for one to two days on Windows systems a blue screen occurs .

**What you expected to happen**:
SMB mounts can be mounted from Windows systems.

**How to reproduce it**:
We use an on-premise Kubernetes cluster running Windows as well as Linux nodes. We have installed the kubectl csi-driver-smb-v0.6.0 in the kube-system namespace, with Windows integration enabled.

In addition, we have created a Storage class and PV/PVCs according to the following templates:

_StorageClass_
``` yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mount-readwritemany
mountOptions:
  - dir_mode=0777
  - file_mode=0777
parameters:
  createSubDir: 'false'
  csi.storage.k8s.io/node-stage-secret-name: mount-secret
  csi.storage.k8s.io/node-stage-secret-namespace: default
  source: \\10.33.3.1\share
provisioner: smb.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
```
_PVC_
``` yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iis-log-web-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: mount-readwritemany
```
_Deployment_
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
      name: web
    spec:
      containers:
        - image: 'webserver:v1'
          name: web
          volumeMounts:
            - mountPath: 'C:\inetpub\logs\LogFiles\W3SVC1'
              name: iis-log-web
      nodeSelector:
        kubernetes.io/os: windows
      volumes:
        - name: iis-log-web
          persistentVolumeClaim:
            claimName: iis-log-web
```

**Anything else we need to know?**:
_Windows Event Log_
![image](https://user-images.githubusercontent.com/15170830/117904565-2d871280-b304-11eb-828a-568ba100583f.png)
![image](https://user-images.githubusercontent.com/15170830/117904608-3ed01f00-b304-11eb-9d6f-c627c65b8aa8.png)
_WinDbg_
![image](https://user-images.githubusercontent.com/15170830/117904884-c453cf00-b304-11eb-8d8b-8730a71b9933.png)
![image](https://user-images.githubusercontent.com/15170830/117904959-e8afab80-b304-11eb-83a9-51c49a501595.png)

**Environment**:
- CSI Proxy version: v0.2.2
- CSI Driver version: v0.6.0
- Kubernetes version: v1.19.10
- OS: Windows Server 2019 Datacenter, Version 1809, OS Build 17763.1817
