### ISSUE TITLE
After installing CSI driver using helm with --set windows.enabled=true, the connection to the ingress controller becomes sporadic

### ISSUE THREAD

**Issue by lesio999** [kubernetes-csi/csi-driver-smb#267]
**What happened**:
Main issue: after installing CSI driver using helm with --set windows.enabled=true, the connection to the ingress controller becomes sporadic. (one request succeeds and the next fails, the third succeeds, the fourth fails. , we used four different types methods to test connection)

**What you expected to happen**:
Expecting to have access to my services via ingress unaffected

**How to reproduce it**:
1. new AKS cluster (1.20.5) with both types of nodes (linux and windows) and running ingress (https://docs.microsoft.com/en-us/azure/aks/ingress-basic)
2. execute few times test-netconnection and ingress demo app - should be no issue
3. install csi driver:
     helm repo add csi-driver-smb https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
     helm install csi-driver-smb csi-driver-smb/csi-driver-smb --namespace kube-system --set windows.enabled=true
4. repeat tests from #2 - some will be ok, some will fail with connection refused error. 

**Anything else we need to know?**:
installing csi driver on linux nodes only - all works just fine

**Environment**:
- CSI Driver version: latest
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"54684493f8139456e5d2f963b23cb5003c4d8055", GitTreeState:"clean", BuildDate:"2021-03-22T23:02:59Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
When install windows driver, it would create a daemonset and expose following two ports on the windows agent node, I think that's the only difference when you set `--set windows.enabled=true`
https://github.com/kubernetes-csi/csi-driver-smb/blob/932dc53fbd1e29334c26b6c71bd2e303310207ff/deploy/csi-smb-node-windows.yaml#L79-L85

**Comment by lesio999** [comment]
We tried the other day with overridden ports --set controller.metricsPort=39644 --set node.metricsPort=39645 as well - still not good.
Where do you think we may have that port collision?
What ports should be open in the linux pod - I see 29643 and 29645.

**Comment by andyzhangx** [comment]
since it's only related to Windows daemonset, would you try replace with other ports(or remove those ports directly) in `csi-smb-node-windows.yaml`, and then `kubectl apply -f csi-smb-node-windows.yaml`

https://github.com/kubernetes-csi/csi-driver-smb/blob/a03a482b5e925a77edcdfbab2ae330be8f5866ff/deploy/csi-smb-node-windows.yaml#L79-L85

**Comment by lesio999** [comment]
I would like to add: this issue looks like is exposed when applied for linux nodes only. I know the title at this point is misleading. Is there anything we can do to troubleshot that? BTW: I installed v1.0.0, no difference, still "locking" our services via ingress.

**Comment by andyzhangx** [comment]
would you try this config, I removed one containerPort and changed another containerPort num:
```yaml
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-smb-node-win
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-smb-node-win
  template:
    metadata:
      labels:
        app: csi-smb-node-win
    spec:
      tolerations:
        - key: "node.kubernetes.io/os"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/os: windows
      priorityClassName: system-node-critical
      containers:
        - name: liveness-probe
          volumeMounts:
            - mountPath: C:\csi
              name: plugin-dir
          image: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.3.0
          args:
            - --csi-address=$(CSI_ENDPOINT)
            - --probe-timeout=3s
            - --health-port=39643
            - --v=2
          env:
            - name: CSI_ENDPOINT
              value: unix://C:\\csi\\csi.sock
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: node-driver-registrar
          image: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.2.0
          args:
            - --v=2
            - --csi-address=$(CSI_ENDPOINT)
            - --kubelet-registration-path=C:\\var\\lib\\kubelet\\plugins\\smb.csi.k8s.io\\csi.sock
          env:
            - name: CSI_ENDPOINT
              value: unix://C:\\csi\\csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: kubelet-dir
              mountPath: "C:\\var\\lib\\kubelet"
            - name: plugin-dir
              mountPath: C:\csi
            - name: registration-dir
              mountPath: C:\registration
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: smb
          image: mcr.microsoft.com/k8s/csi/smb-csi:latest
          imagePullPolicy: IfNotPresent
          args:
            - --v=5
            - --endpoint=$(CSI_ENDPOINT)
            - --nodeid=$(KUBE_NODE_NAME)
          ports:
            - containerPort: 39643
              name: healthz
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
          env:
            - name: CSI_ENDPOINT
              value: unix://C:\\csi\\csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: kubelet-dir
              mountPath: "C:\\var\\lib\\kubelet"
            - name: plugin-dir
              mountPath: C:\csi
            - name: csi-proxy-fs-pipe
              mountPath: \\.\pipe\csi-proxy-filesystem-v1beta1
            - name: csi-proxy-smb-pipe
              mountPath: \\.\pipe\csi-proxy-smb-v1beta1
          resources:
            limits:
              cpu: 400m
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 20Mi
      volumes:
        - name: csi-proxy-fs-pipe
          hostPath:
            path: \\.\pipe\csi-proxy-filesystem-v1beta1
            type: ""
        - name: csi-proxy-smb-pipe
          hostPath:
            path: \\.\pipe\csi-proxy-smb-v1beta1
            type: ""
        - name: registration-dir
          hostPath:
            path: C:\var\lib\kubelet\plugins_registry\
            type: Directory
        - name: kubelet-dir
          hostPath:
            path: C:\var\lib\kubelet\
            type: Directory
        - name: plugin-dir
          hostPath:
            path: C:\var\lib\kubelet\plugins\smb.csi.k8s.io\
            type: DirectoryOrCreate
```
