### ISSUE TITLE
Dynamic provisioning successful but smbSubFolder not created in stead PVs mounted directly in root of share

### ISSUE THREAD

**Issue by bambam247** [kubernetes-csi/csi-driver-smb#307]
**What happened**:
smbSubFolder not created
**What you expected to happen**:
smbSubFolder created with name of PV

**How to reproduce it**:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dsm-cifs-pg
provisioner: smb.csi.k8s.io
parameters:
  source: "//smb-server.default.svc.cluster.local/share"
  # if csi.storage.k8s.io/provisioner-secret is provided, will create a sub directory
  # with PV name under source
  csi.storage.k8s.io/provisioner-secret-name: "smbcreds"
  csi.storage.k8s.io/provisioner-secret-namespace: "nondefault"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "nondefault"
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0700
  - file_mode=0700
  - uid=101
  - gid=103
```

basically following the e2e example

**Anything else we need to know?**:
pv created succesfully, db init seems successful also, however I am not sure it is intended for both nodes (postgresql in this case) to see the exact same folder on the smb server. I would expect the subfolder to be created with the name of the PV as the comment suggests.

**Environment**:
2 node cluster
                                   
- CSI Driver version:
latest master / v1.0.0
- Kubernetes version (use `kubectl version`):
Server Version: version.Info", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e30
7844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d96
1e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"
- OS (e.g. from /etc/os-release):
Ubuntu 20.10
- Kernel (e.g. `uname -a`):
Linux mmj-mstr-01 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Other
Using `createSubDir: "true"` parameter setting results in
_failed to provision volume with StorageClass "dsm-cifs-pg": rpc error: code = Unknown desc = invalid parameter createSubDir in storage class_ (same results for release v1.0.0)
