### ISSUE TITLE
Chart does not allow the DaemonSet deployment strategy to be customized

### ISSUE THREAD

**Issue by juliohm1978** [kubernetes-csi/csi-driver-smb#334]
**Is your feature request related to a problem?/Why is this needed**
No. This is just an improvement to the helm chart, to customize the deployment of the current version.

**Describe the solution you'd like in detail**
The default DaemonSet stragey limits unavailable pods to 1.

```yaml
kind: DaemonSet
  spec:
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 1
      type: RollingUpdate
```

Since the chart does not provide any values for that, the k8s defaults are used. I would like the chart to allow this value to be customized. On large clusters (say: 10+ nodes), a simple rolling update can take several minutes. It would be great to allow more pods to terminate at the same time.

**Describe alternatives you've considered**
Currently, the only alternative is to not use the helm chart and deploy the driver using pure k8s manifests.
