### ISSUE TITLE
Write a samba server kubernetes deployment

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-smb#36]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

could refer to https://hub.docker.com/r/servercontainers/samba
there is also a reference here: https://github.com/dperson/samba

And there is also a working example here: https://github.com/kubernetes-csi/csi-driver-smb/pull/34, this example just uses docker, need to change to k8s deployment, leverage a local hostpath.

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
Here is the draft one,  basic mount succeeds, while it still has `Permission denied` issue, also need to store username, password in k8s secret, could refer to https://github.com/andyzhangx/demo/tree/master/examples/postgresql

Could you refine it? @Sakuralbj thanks.

```yaml
---
kind: Service
apiVersion: v1
metadata:
  name: smb-server
  labels:
    app: smb-server
spec:
  type: LoadBalancer
  selector:
    app: smb-server
  ports:
    - port: 445
      name: smb-server
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: smb-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smb-server 
  template:
    metadata:
      name: smb-server
      labels:
        app: smb-server
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: smb-server
        image: dperson/samba
        args: ["-u", "username;test","-s", "share;/smbshare/;yes;no;no;all;none"]
        volumeMounts:
        - mountPath: /smbshare
          name: data-volume
        ports:
        - containerPort: 445
      volumes:
      - name: data-volume
        hostPath:
          path: /smbshare
          type: DirectoryOrCreate
```
