### ISSUE TITLE
spec.volumes[0]: Required value: must specify a volume type

### ISSUE THREAD

**Issue by omerozery** [kubernetes-csi/csi-driver-smb#367]
**What happened**:
* spec.volumes[0]: Required value: must specify a volume type

**What you expected to happen**:
storage layer to be created pvc and pv

**How to reproduce it**:
just copy paste the generic ephemeral volume example from the docs.
https://v1-20.docs.kubernetes.io/docs/concepts/storage/ephemeral-volumes/
kubectl apply the below:
```
kind: Pod
apiVersion: v1
metadata:
  name: my-app
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/scratch"
        name: scratch-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: scratch-volume
      ephemeral:
        volumeClaimTemplate:
          metadata:
            labels:
              type: my-frontend-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "scratch-storage-class"
            resources:
              requests:
                storage: 1Gi
```
**Anything else we need to know?**:
that is probably not a direct issue of csi-driver-smb, since the pod manifest validation is failing, before the pod manifest is applied and the driver takes action...

**Environment**:
- CSI Driver version: v1.4.0
- Kubernetes version (use `kubectl version`): Kubernetes 1.20.2
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`): 3.10.0-1127.19.1.el7.x86_64
- Install tools:
- Others:
