### ISSUE TITLE
arm64 broken since v1.3.0

### ISSUE THREAD

**Issue by willat8** [kubernetes-csi/csi-driver-smb#383]
Looks like c1a65f8 swapped the registry to MCR which doesn't provide arm64 images. v1.2.0 and below works fine on arm64.

**Comment by andyzhangx** [comment]
which tag are you trying? `mcr.microsoft.com/k8s/csi/smb-csi:v1.4.0` should has arm64 image:
```yaml
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1375,
         "digest": "sha256:0b378bb08be4b3f28fd73d13b28d7286f93400a45bf97725e931b3261d35de11",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1375,
         "digest": "sha256:c04a8af518ace4e845f5fad7ea8a2263c47cd70a36a51851aea335551e51df46",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1375,
         "digest": "sha256:2cd54e39e79d6a3823397a5aad01bfa917b6a1c4310057734a852f1dbe8198be",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
```

```console
docker inspect mcr.microsoft.com/k8s/csi/smb-csi:v1.4.0-linux-arm64
...
        "Architecture": "arm64",
        "Os": "linux",
```
