### ISSUE TITLE
[feature request] Dynamic provisioning of PVs referring existing SMB shares of NAS filers

### ISSUE THREAD

**Issue by ppenzo** [kubernetes-csi/csi-driver-smb#398]
**Is your feature request related to a problem?/Why is this needed**
This driver can be use to dynamically create PV as a subpath of an existing SMB share but it cannot be used to dynamically create PV referencing existing shares since it does not handles extra parameters in the storageclass definition.

**Describe the solution you'd like in detail**
Dynamic provisioning of PV referring existing shares could be achieved by indicating the share name into the PVC (for instance using a specific annotation) and then by introducing a parameter into the storageclass definition allowing the share name indicated by the PVC to be honored.

**Describe alternatives you've considered**
Per share PVs can be manually created but this requires cluster-admin privileges and a lot of manual work and time.

**Additional context**
This feature is suited for NAS filers and it assumes that each NAS node has its own storageclass definition.

**Comment by andyzhangx** [comment]
you mean add a `volumeAttributes.folderName` in PV setting? is it possible addpend folderName into `volumeAttributes.source`?

https://github.com/kubernetes-csi/csi-driver-smb/blob/1e388744b4fcc9bb29388833db80ecac9403caf0/deploy/example/pv-smb.yaml#L16-L21

**Comment by ppenzo** [comment]
Not exactly.
The one  you pointed out is the manual PV definition which IMHO tought to maintain and which requires cluster admin privilege, at least on Openshift,  since it is related to the PV creation.
I would like to implement a dynamic creation of these PVs using PV claimns and storageclasses:
```

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    csi-smb/storagepath: myNASShare
  name: NASfilerpvc
spec:
  storageClassName: NASfilernode01
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: NASfilernode01
provisioner: smb.csi.k8s.io
reclaimPolicy: Delete
parameters:
  source: "//myNASfilerNode01/"
  shareName: ${pvc.annotations['csi-smb/storagepath']}
  csi.storage.k8s.io/provisioner-secret-name: "smbcreds"
  csi.storage.k8s.io/provisioner-secret-namespace: "defaults"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "application-ns"
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
```

Obviously the SMB path //myNASfilerNode01/myNASShare must be existing and accessible with the credentials provided by the application.
