### ISSUE TITLE
Cannot mount an existing share via subDir parameter

### ISSUE THREAD

**Issue by ppenzo** [kubernetes-csi/csi-driver-smb#428]
**What happened**:
The subDir parameter is not honoured in PVC and, when used in a storage class causes all the volumes to be attached to the share/directory specified in the SC definition.

**What you expected to happen**:
AFAIK the subDir parameter should allow the PVC to request a volume bounded to an existing share as per issue [#398]

**How to reproduce it**:
To reproduce just define a SC like this
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-csi-smb
provisioner: smb.csi.k8s.io
reclaimPolicy: Delete
parameters:
  source: "//NAS_FILER/"
  subDir: "TESTSHARE"
  csi.storage.k8s.io/provisioner-secret-name: "smbcreds"
  csi.storage.k8s.io/provisioner-secret-namespace: "aatest-storage"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "aatest-storage"
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
```

and a PVC like this 
```

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-tsmb-12
spec:
  storageClassName: test-csi-smb
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  csi:
    volumeAttributes:
      subDir: "anotherSHARE"

```
As a result the volume will be bounded to //NAS_FILER/TESTSHARE and not to //NAS_FILER/anotherSHARE.
The same occurs when the subDir parameters is not specified into the PVC.

**Anything else we need to know?**:
Not defining the subDir parameter into the SC causes the PV to be bounded to a subdirectory of //NAS_FILER/TESTSHARE created "on the fly" no matter if the volumeAttributes.subDir parameters is defined into the PVC.

Also defining the volumeAttributes.source into the PVC has no effect.

**Environment**:
- CSI Driver version: 1.5.0

**Comment by andyzhangx** [comment]
I think this driver only honors `subDir: "TESTSHARE"` in storage class, it won't honor `volumeAttributes` in `PersistentVolumeClaim`. btw, is this pvc config valid?
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-tsmb-12
spec:
  storageClassName: test-csi-smb
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  csi:
    volumeAttributes:
      subDir: "anotherSHARE"
```

```console
# k apply -f /tmp/a.yaml
error: error validating "/tmp/a.patch2": error validating data: ValidationError(PersistentVolumeClaim.spec): unknown field "csi" in io.k8s.api.core.v1.PersistentVolumeClaimSpec; if you choose to ignore these errors, turn validation off with --validate=false
```
