### ISSUE TITLE
Setting affinity on node not working (resulting in validating error)

### ISSUE THREAD

**Issue by aymenfurter** [kubernetes-csi/csi-driver-smb#490]
**What happened**:
Configuring affinity on the csi-smb-node daemonset does not work. Using the following configuration:
`node.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key=agentpool`
`node.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].operator=In`
`node.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values={foobar}`

results in the following error message:
`error validating data: ValidationError(DaemonSet.spec.template.spec.nodeSelector.nodeAffinity): invalid type for io.k8s.api.core.v1.PodSpec.nodeSelector: got "map", expected "string"`

**What you expected to happen**:
I would have expected that the following YAML would be generated:
 ```
   spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - foobar
```

**How to reproduce it**:
Deploy Helm Chart with affinity configuration on node level (See above)

**Anything else we need to know?**:
not needed

**Environment**:
- CSI Driver version: 1.7.0
- Kubernetes version (use `kubectl version`): v1.23.5
- OS (e.g. from /etc/os-release): Ubuntu 18.04 LTS
- Kernel (e.g. `uname -a`): 5.4.0
- Install tools: ?
- Others:
