### ISSUE TITLE
Templated Share Subdirectory

### ISSUE THREAD

**Issue by MiddleMan5** [kubernetes-csi/csi-driver-smb#502]
**Is your feature request related to a problem?/Why is this needed**

We have a number of SMB NAS systems that we use as cluster-wide, general purpose storage, but provisioning sub-directories for each application is time-consuming and error prone and requires a human admin to configure. 

As of now, we have to define a csi-smb-provisioned StorageClass per application deployment just to reliably control the directory that an application stores it's data in which again requires another additional cluster-admin step. 

**Describe the solution you'd like in detail**
Ideally, a StorageClass could define a "subDir" template string that allows the admin to control how a new PVC is allocated a SMB share. 

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-auto
provisioner: smb.csi.k8s.io
parameters:
  source: "//mynas.my.domain/storage/root"
  subDir: "smb-auto-${pvc.annotations['app.kubernetes.io/instance']}"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "storage"
```

Given the above as an example of suggested syntax, The following additional use cases should be taken into consideration: 

A unique share name per pvc:
Given: `subDir: "smb-auto-${pvc.metadata.name}"`
Result: `//mynas.my.domain/storage/root/smb-auto-pvc-95f1d979-9cb2-4a84-90ed-5d25cebeccc4` 

Namespace-specific shared storage:
Given:  `subDir: "smb-auto-${pvc.metadata.namespace}"` 
Result: `//mynas.my.domain/storage/root/smb-auto-production`

A shared storage share that multiple pods of the same deployment share 
Given: `subDir: "smb-auto-${pvc.annotations['app.kubernetes.io/instance']}"`
Result: `//mynas.my.domain/storage/root/smb-auto-nginx-frontend`

**Describe alternatives you've considered**
This feature request appears to be related to the discussion under issue #428 

**Additional context**
Kubernetes 1.23
