### ISSUE TITLE
Use servercontainers/samba image

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-smb#52]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

Currently we are using `dperson/samba` image in SMB server set up example, it's better switch to use `servercontainers/samba` image: https://hub.docker.com/r/servercontainers/samba

https://github.com/kubernetes-csi/csi-driver-smb/blob/1a825f4aa4b1ab3a6b03db9800c59a2f05b1660e/deploy/example/smb-provisioner/smb-server.yaml#L33

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
cc @animeshk08

**Comment by animeshk08** [comment]
Updates server set up using `servicecontainers/samba`:
```
---
kind: Service
apiVersion: v1
metadata:
  name: smb-server
  labels:
    app: smb-server
spec:
  type: ClusterIP # use "LoadBalancer" to get a public ip
  selector:
    app: smb-server
  ports:
    - port: 445
      name: smb-server
      targetPort: 445
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: smb-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smb-server
  template:
    metadata:
      name: smb-server
      labels:
        app: smb-server
    spec:
      containers:
        - name: smb-server
          image: servercontainers/samba
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: smbcreds
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smbcreds
                  key: password
            - name: ACCOUNT_USERNAME # Need to figure out how to add user from secret here
              value: $(PASSWORD)
            - name: SAMBA_VOLUME_CONFIG_username # Need to figure out how to add user from secret here
              value: '[$(USERNAME) share]; path=/smbshare/; guest ok
            = no; read only = no; browseable = yes'
          volumeMounts:
            - mountPath: /smbshare
              name: data-volume
          ports:
            - containerPort: 445
      volumes:
        - name: data-volume
          hostPath:
            path: /smbshare-volume  # modify this to specify another path to store smb share data
            type: DirectoryOrCreate

```

Currently, the `username` is not being set from the K8s secret. It is directly read using the K8s deployment. If the `env` variable name is  `ACCOUNT_TEST` the username will be `test`. Similarly the `SAMBA_VOLUME_CONFIG_` is also username dependent, which is currently hardcoded and not being read from the secret.
