### ISSUE TITLE
Publish helm chart on ArtifactHub

### ISSUE THREAD

**Issue by k-jingyang** [kubernetes-csi/csi-driver-smb#568]
**Is your feature request related to a problem?/Why is this needed**
Our team is using this Helm chart in our on-prem environment but bringing the chart in currently requires a workaround.

There's an established flow where we mirror in Helm charts from [ArtifactHub](https://artifacthub.io/).

**Describe the solution you'd like in detail**

Would it be possible to publish the helm chart onto ArtifactHub as a verified repository?

**Comment by andyzhangx** [comment]
@k-jingyang what's the process to publish helm chart to ArtifactHub?

**Comment by k-jingyang** [comment]
You will have to 
1. Login to https://artifacthub.io/
2. Top right hand corner, profile button > `Control Panel`
3. Assuming you wanna publish it under your name, go to `Repositories` tab > `Add Repository`
    - Fill in the details
    - For URL, it should be https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts

Once this is done, you can create an `artifacthub-repo.yml` file in the `csi-driver-smb/charts/` folder in the `master` branch

```yaml
# Artifact Hub repository metadata file
repositoryID: The ID of the Artifact Hub repository
owners: # (optional, used to claim repository ownership)
  - name: xxx
    email: xxx
```

[Here](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/gh-pages/charts/artifacthub-repo.yml) is another example from an Azure repo. In this case, they're on the gh-pages branch since they're hosting their charts there.

Hope this helps! Thanks a bunch! :smile:
