### ISSUE TITLE
provide storage class support

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-smb#60]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

We could provide storage class support even it's static provisioning, and then this driver would pass storage parameters to `NodeStageVolume`

refer to https://kubernetes-csi.github.io/docs/secrets-and-credentials-storage-class.html
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb
provisioner: smb.csi.k8s.io
parameters:
  source: "//smb-server.default.svc.cluster.local/share"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "default"
reclaimPolicy: Retain # can only support retain
volumeBindingMode: Immediate
```

**Describe alternatives you've considered**

**Additional context**
