### ISSUE TITLE
Dynamic provisioning: subdir created, but not visible/mounted inside pod

### ISSUE THREAD

**Issue by boekhold** [kubernetes-csi/csi-driver-smb#674]
I'm stuck on a dynamically provisioned PVC not actually showing inside my pod. Any files I place inside the dynamically created subdir are not visible inside my pod, and any files created inside the pod and placed under the mount path are not created on the SMB fileserver. It 

**What happened**:
Dynamically provisioned PV/PVC is not mounted in pod.

**What you expected to happen**:
SMB share is mounted inside pod

**Environment**:
v1.12.0
Kubernetes 1.25 (microk8s)
RHEL 8.8
Kernel 4.18.0-477.21.1.el8_8.x86_64

Samba server installed on Linux RHEL 8.8, with a share defined as:
```
[dynamic-share]
        path = /data/smb-share
        read only = No
        valid users = myuser
        create mask = 0644
        directory mask = 0755
        force user = myuser
```

Storage class defined as:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: smb-dynamic
provisioner: smb.csi.k8s.io
parameters:
    source: "//smbserver/dynamic-share"
    subDir: ${pvc.metadata.namespace}-${pvc.metadata.name}-${pv.metadata.name}
    csi.storage.k8s.io/provisioner-secret-name: "smb-secret"
    csi.storage.k8s.io/provisioner-secret-namespace: "kube-system"
    csi.storage.k8s.io/node-stage-secret-name: "smb-secret"
    csi.storage.k8s.io/node-stage-secret-namespace: "kube-system"
reclaimPolicy: Retain     # only Retain is supported
volumeBindingMode: Immediate
# I've been trying various different mount options...
mountOptions:
    - vers=3.0
    - dir_mode=0777
    - file_mode=0777
    #- uid=1001
    #- gid=1001
```

A PVC has been created as:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  storageClassName: smb-dynamic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

A deployment has been created as:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
spec:
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: test-pvc
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: pvc
          mountPath: /usr/share/nginx/html
```

After applying the above configuration, I can see that a subdir is created on the Samba server side:
```
$ ls /data/smb-share
default-test-pvc-pvc-1f67b01d-8254-47d4-9780-12720cac108f
$
```

Exec'ing into the nginx pod: `kubectl exec -it test-nginx -- /bin/bash`
```
$ kubectl exec -it test-nginx -- /bin/bash
root@test-nginx:/# ls /usr/share/nginx/html
root@test-nginx:/# touch /usr/share/nginx/html/FOOBAR
root@test-nginx:/# ls /usr/share/nginx/html
FOOBAR
root@test-nginx:/# exit
$ ls -la /data/smb-share/default-test-pvc-pvc-1f67b01d-8254-47d4-9780-12720cac108f
# NO RESULTS, the FOOBAR file created inside the pod does not show up on the SMB share
$ touch /data/smb-share/default-test-pvc-pvc-1f67b01d-8254-47d4-9780-12720cac108f/BARFOO
$ kubectl exec -it test-nginx -- /bin/bash
root@test-nginx:/# ls /usr/share/nginx/html
FOOBAR
# The BARFOO file created directly on the Samba server does not show in the pod
# exit
``` 

I _CAN_ however see the actual contents of the SMB share in the _csi-smb-node_:
```
$ kubectl exec -it csi-smb-node-d97c5 -n kube-system -c smb -- /bin/sh
# ls /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/smb.csi.k8s.io/4bbbfd48638ddebb541deed1ed94f539a3b4edb5954774e8255f149e471b679a/globalmount
BARFOO
# ls /var/snap/microk8s/common/var/lib/kubelet/pods/08dd663f-fe76-41e5-b529-3687b49ad5b7/volumes/kubernetes.io~csi/pvc-1f67b01d-8254-47d4-9780-12720cac108f/mount
BARFOO
# exit
```
I appreciate any help to solve this issue. The reason I really need this to work is that I am forced to switch away from the nsf-subdir-provider because NFS servers are being flagged as a security risk inside our organization.
