### ISSUE TITLE
microk8s + kerberos integration issues

### ISSUE THREAD

**Issue by fabioscaccabarozzi** [kubernetes-csi/csi-driver-smb#705]
**What happened**: when trying to setup PV+PVC with Kerberos under microk8s, nodes cannot mount the share, and pods stay in "ContainerCreating" state, until they fail and are restarted.

**What you expected to happen**: share is mounted fine, pods can correctly start

**How to reproduce it**:
--------------------------
**Steps to reproduce**
Assuming we're on a host where Kerberos is configured, and `cifs-utils` and `keyutils` are installed.
Install microk8s via snap: `snap install microk8s --classic`
Install CSI driver with values supplied below.
[Use the driver-parameters docs for the kerberos part (kinit, secret, ...)](https://github.com/kubernetes-csi/csi-driver-smb/blob/master/docs/driver-parameters.md)
Create the resources below. PV and PVC will show "Bound".
Attempt to create a deployment that uses the PVC (see example below).
Whichever node attempts to run the pod will fail with the following error:
```shell
microk8s.daemon-kubelite[1422]: E1212 11:06:34.115973    1422 csi_attacher.go:364] kubernetes.io/csi: attacher.MountDevice failed: rpc error: code = Internal desc = Error writing kerberos cache: rpc error: code = Internal desc = Directory for kerberos caches must exist, it will not be created: /var/lib/kubelet/kerberos/: stat /var/lib/kubelet/kerberos/: no such file or directory
```

--------------------------
**Investigation & Explanation**
In microk8s, by default `/var/lib/kubelet` is a symlink pointing to `/var/snap/microk8s/common/var/lib/kubelet`.
Kerberos was configured according to the driver-parameter docs linked above, so we have:
```shell
[libdefaults]
        debug = true
        default_realm = <realm.com>
        default_ccache_name = FILE:/var/lib/kubelet/kerberos/krb5cc_%{uid}
        kdc_timesync = 1
        ccache_type = 4
        forwardable = true
        proxiable = true

[realms]
...
[domain_realm]
...
```

The first problem is that if we supply `linux.kubelet` at chart installation, that folder will be [mounted by the chart](https://github.com/kubernetes-csi/csi-driver-smb/blob/master/charts/v1.13.0/csi-driver-smb/templates/csi-smb-node.yaml#L137) in the `csi-smb-node` pod verbatim via hostPath (host: /path/A -> pod: /path/A).

The second problem is we can't seem to find a way to alter [the Kerberos cache path](https://github.com/kubernetes-csi/csi-driver-smb/blob/master/pkg/smb/smb.go#L42). This means that if we move the kubelet path via `linux.kubelet`, the `/var/lib/kubelet` path won't exist in the `csi-smb-node` pods, making it impossible to create and save kerberos tickets from the pod to the host system, which ultimately is the one performing the mounts via `cifs-utils`.

Further, currently in the Kerberos cache folder **absolute** symlinks are used from `krb5cc_UID` files to the actual token files (e.g: `/var/lib/kubelet/kerberos/krb5cc_1000` -> `/var/lib/kubelet/kerberos/aW1nLXNoYXJlLWRldm1xcw==`), so the source path from the host must be exactly the same *also in the pod*, otherwise the absolute symlinks won't work for `cifs-utils`.

As it stands now, `csi-smb-node` expects the the kerberos cache to be at `/var/lib/kubelet/kerberos` and nowhere else, making it impossible the use of Kerberos with a different `linux.kubelet`.

--------------------------
**Fixing attempt**
I have tried to modify the helm chart template for `csi-smb-node` to mount the Kerberos cache folder as an additional volume, or the same volume with subPath, but it doesn't work -> `touch /var/lib/..../kerberos/test` would yield `no such file or directory`, I guess because I cannot mount the same path twice for the same pod. Anyway that would clash with the hard-coded path in the file referenced above.

--------------------------
**Proposed solution**
The better solution would be to make the Kerberos cache path configurable as the `linux.kubelet` path is, and ideally discourage the use of `/var/lib/kubelet/kerberos`, as in microk8s that path is a symlink to the snap folder.

--------------------------
**Objects used**
The helm chart values, as per docs for microk8s:
```
$ helm get values -nkube-system csi-driver-smb
USER-SUPPLIED VALUES:
linux:
  kubelet: /var/snap/microk8s/common/var/lib/kubelet
```

These are the credentials, PV and PVC I'm trying to use:
```yaml
apiVersion: v1
kind: Secret
stringData:
  krb5cc_1000: __SMB_SHARE_KRB5CC__
metadata:
  name: smbcreds-krb5
  namespace: proj-ns
type: Opaque
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb-krb5
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino # required to prevent data corruption
    - sec=krb5
    - uid=1000
    - cruid=1000
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: pv-proj-ns-krb5 # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "__SMB_SHARE_URL__"
    nodeStageSecretRef:
      name: smbcreds-krb5
      namespace: proj-ns
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb-krb5
  namespace: proj-ns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-smb-krb5
  storageClassName: smb
```

An example deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj-deploy
  namespace: proj-ns
spec:
  selector:
    matchLabels:
      name: proj-deploy
  replicas: 2
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        name: proj-deploy
    spec:
      restartPolicy: Always
      volumes:
        - name: smb
          persistentVolumeClaim:
            claimName: pvc-smb-krb5
      containers:
        - name: test-deploy
          image: nginx
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /data
              name: smb
```

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: csi-driver-smb-v1.13.0
- Kubernetes version (use `kubectl version`): 1.27.8 (snap)
- OS (e.g. from /etc/os-release): Ubuntu 20.04 LTS
- Kernel (e.g. `uname -a`): 5.4.0-169-generic
