### ISSUE TITLE
Issue with credential on windows node and pods 

### ISSUE THREAD

**Issue by baptiste-xaxa** [kubernetes-csi/csi-driver-smb#885]
### Environment:

CSI Driver version: 1.16.0
Kubernetes version (use kubectl version): 1.29.9
OS (e.g. from /etc/os-release): Windows Server 2022
Pods: mcr.microsoft.com/windows/servercore:ltsc2022
windows csi proxy : 1.1.3

### Problems

When i create a storage class smb + smbcreds, i can mount pvc in linux pod, but i'am not able to mount PVC in windows pods.

###  Problems

This function is used to mount samba share on windows pods:

`vendor/k8s.io/mount-utils/mount_windows.go`

```
// do the SMB mount with username, password, remotepath
// return (output, error)
func newSMBMapping(username, password, remotepath string) (string, error) {
        if username == "" || password == "" || remotepath == "" {
                return "", fmt.Errorf("invalid parameter(username: %s, password: %s, remoteapth: %s)", username, sensitiveOptionsRemoved, remotepath)
        }

        // use PowerShell Environment Variables to store user input string to prevent command line injection
        // https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-5.1
        cmdLine := `$PWord = ConvertTo-SecureString -String $Env:smbpassword -AsPlainText -Force` +
                `;$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $Env:smbuser, $PWord` +
                `;New-SmbGlobalMapping -RemotePath $Env:smbremotepath -Credential $Credential -RequirePrivacy $true`
        cmd := exec.Command("powershell", "/c", cmdLine)
        cmd.Env = append(os.Environ(),
                fmt.Sprintf("smbuser=%s", username),
                fmt.Sprintf("smbpassword=%s", password),
                fmt.Sprintf("smbremotepath=%s", remotepath))

        output, err := cmd.CombinedOutput()
        return string(output), err
}
```

It use secrets to get username, password and remote path:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: smbcreds
  namespace: kube-system
type: Opaque
stringData:
  username: 'login'
  password: "xxxxxxxx"
```

Problem:

`New-SmbGlobalMapping`  expect (mandatory)  username with WORKGROUP\login

Issue:

If i change secret with 

```
---
apiVersion: v1
kind: Secret
metadata:
  name: smbcreds
  namespace: kube-system
type: Opaque
stringData:
  username: 'WORKGROUP\login'
  password: "xxxxxxxx"
```

There is a substitution issue. On my samba server logs i can see that user login is 'WORKGROUP\login' instead of 'login'.

and when i try manually (inside my pod in powershell)

```
$User = "WORKGROUP\login"
$Password = "xxxxx"
$PWord = ConvertTo-SecureString -String $Password -AsPlainText -Force
$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $User, $PWord
New-SmbGlobalMapping -RemotePath "\\192.168.2.61\samba" -Credential $Credential -RequirePrivacy $true
```

it work fine (in my samba server log, user login is 'login' and not of 'WORKGROUP\login'

I dont know what append to string `$Env:smbuser` but when passed to the function, there is a problem
