### ISSUE TITLE
mapping key "securityContext" already defined at line 40 when installing v1.17.0

### ISSUE THREAD

**Issue by smaugs** [kubernetes-csi/csi-driver-smb#916]
**What happened**:
When installing the Release 1.17.0 the following error is thrown:

```
Helm install failed for release kube-system/csi-driver-smb with chart csi-driver-smb@v1.17.0: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
          line 44: mapping key "securityContext" already defined at line 40
```

**What you expected to happen**:
Install without errors

**How to reproduce it**:
Installed with FluxCD and the following manifest, in fact should be the same as normal helm install with option "controller.runOnControlPlane=true"

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: kube-system
spec:
  chart:
    spec:
      chart: csi-driver-smb
      version: v1.17.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
  interval: 1h0m0s
  values:
    controller:
      runOnControlPlane: true
```

**Anything else we need to know?**:
v1.16.0 works without any problems

**Environment**:

- CSI Driver version: not installed
- Kubernetes version (use `kubectl version`):
```
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.28.7
```
- OS (e.g. from /etc/os-release): Talos Linux 1.8
- Kernel (e.g. `uname -a`): should not be relevant
- Install tools:
- Others:
