### ISSUE TITLE
using smb csi driver and unable to list or touch netapp cifs share from within POD

### ISSUE THREAD

**Issue by antak6** [kubernetes-csi/csi-driver-smb#946]
Hi Team,

We have a windows user with full control and that user can access NetApp CIFS share via windows explorer. We are using smb csi driver v1.17.0. We have mounted the NetApp CIFS svm and can reach the mount point but get permission denied to ls or touch inside the netapp cifs mount. Can anyone confirm if SMB CSI driver works for NetApp CIFS shares? If we try to do exact same thing using same driver for a normal windows file share, it does work. We have checked all NetApp and user account details and nothing more to be done on those ends.

**Comment by andyzhangx** [comment]
@antak6 does ls or touch work if you mount smb share on the windows node directly?
```
$User = "Domain\USERNAME"
$PWord = ConvertTo-SecureString -String "PASSWORD" -AsPlainText -Force
$Credential = New-Object –TypeName System.Management.Automation.PSCredential –ArgumentList $User, $Pword
New-SmbGlobalMapping -LocalPath x: -RemotePath \\smb-server\fileshare -Credential $Credential
Get-SmbGlobalMapping
cd x:
dir
```

**Comment by antak6** [comment]
Yes, it does work with same credentials from windows UNC ... So I guess this is not a SMB csi issue .. probably it is something to do with how netapp is translating or not translating/mapping LINUX UIDs to windows user .. I will close this issue since it is not related to SMB CSI anymore. 

> [@antak6](https://github.com/antak6) does ls or touch work if you mount smb share on the windows node directly?
> 
> ```
> $User = "Domain\USERNAME"
> $PWord = ConvertTo-SecureString -String "PASSWORD" -AsPlainText -Force
> $Credential = New-Object –TypeName System.Management.Automation.PSCredential –ArgumentList $User, $Pword
> New-SmbGlobalMapping -LocalPath x: -RemotePath \\smb-server\fileshare -Credential $Credential
> Get-SmbGlobalMapping
> cd x:
> dir
> ```

**Comment by antak6** [comment]
Re-opening since we did a lot of troubleshooting around this. We are able to manually mount the netapp cifs share inside the POD and also on the kubernetes node. However, when we define it in yaml files for csi driver to do the actual mounting, it doesn't work and gives permission denied.

**Comment by antak6** [comment]
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-sc-test
provisioner: smb.csi.k8s.io
parameters:
  csi.storage.k8s.io/provisioner-secret-name: smb-credentials
  csi.storage.k8s.io/provisioner-secret-namespace: my-cifs-namespace
  csi.storage.k8s.io/node-stage-secret-name: smb-credentials
  csi.storage.k8s.io/node-stage-secret-namespace: my-cifs-namespace
  source: //my_netapp_share_path
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - nobrl
  - version=3.0
  - noperm
---
apiVersion: v1
kind: Secret
metadata:
  name: smb-credentials-test
  namespace: my-cifs-namespace
type: Opaque
stringData:
  password: My_PWD
  username: My_User
---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: smb-pvc-test
#  namespace: my-cifs-namespace
#spec:
#  storageClassName: smb-sc-test
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 5Gi
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: smb-pvc-test
  namespace: my-cifs-namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-smb-test
  storageClassName: smb-sc-test
---
apiVersion: v1
kind: Pod
metadata:
  name: smb-test-pod-test
  namespace: my-cifs-namespace
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  containers:
  - name: test-container
    image: My_Image_repo_link
    command: ["/bin/sleep", "infinity"]
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "200m"
        memory: "256Mi"
    volumeMounts:
    - name: smb-volume
      mountPath: /tmp/test
      readOnly: false
  volumes:
  - name: smb-volume
    persistentVolumeClaim:
      claimName: smb-pvc-test
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: pv-smb-test
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb-sc-test
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: my_netapp_share_path 
    readOnly: false
    volumeAttributes:
      source: "//my_netapp_share_path/"
    nodeStageSecretRef:
      name: smb-credentials-test
      namespace: my-cifs-namespace
```
