### ISSUE TITLE
Error: could not get secret

### ISSUE THREAD

**Issue by Ergamon** [kubernetes-csi/csi-driver-smb#950]
I have the need to mount a windows share in my cluster so I stumbled accross this driver.

My setup:
- Kubernetes 1.33.0
- csi-driver-smb v1.17.0 installed via helm chart (no modification to any values)

I wanted to start with something simple and created a namespace test and a secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: smbcreds
  namespace: test
stringData:
  username: "username"
  password: "password"
```
and a pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: smbpod
  namespace: test
spec:
  containers:
  - name: busybox
    image: busybox
    command: [ "sleep", "3600" ]
    volumeMounts:
    - name: smb
      mountPath: /mnt/smb
  volumes:
  - name: smb
    csi:
      driver: smb.csi.k8s.io
      volumeAttributes:
        source: "//WINDOWS-SERVER-IP/ShareName"
        mountOptions: "dir_mode=0777,file_mode=0777"
      nodePublishSecretRef:
        name: smbcreds
```

Wenn I do a 
```
kubectl describe pod smbpod -n test
```
I get this:

```
  Warning  FailedMount  83s (x9 over 3m31s)  kubelet            MountVolume.SetUp failed for volume "smb" : rpc error: code = Internal desc = Error getting username and password from secret  in namespace test: could not get secret(): resource name may not be empty
```

Am I doing something wrong or using something not supported?

The message looks like the driver cannot read the secret.
